name: Build and Test on Docker
on:
  push:
    branches: 
      - main
      - ci
  pull_request:
    branches: 
      - main
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

env:
  TEST_TAG: roboml/app:test
  LATEST_TAG: roboml/app:latest

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and export to Docker
        uses: docker/build-push-action@v5
        with:
          context: .github/workflows/.
          load: true
          tags: ${{ env.TEST_TAG }}
      - name: Test
        run: |
          docker run --rm ${{ env.TEST_TAG }} \
          sudo chmod +rwx ./build_and_test.sh \
          && sudo chmod +rwx /usr/local/
          && sudo sh ./build_and_test.sh 