name: "arm64 | x86_64 "
on:
  push:
    branches: 
      - main
      - ci
  pull_request:
    branches: 
      - main
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

env:
  TEST_TAG: roboml/app:test
  LATEST_TAG: roboml/app:latest

jobs:
  docker:
    name: ${{ matrix.cpu_arch.cmake }}, CXX=${{ matrix.cxx }},{{ matrix.cmake }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cpu_arch:
          - name: arm
            docker: arm64v8
            cmake: aarch64
          - name: x86_64
            docker: amd64
            cmake: x86_64
        cxx: [17, 20] # [11, 14, 17, 20]
        cmake:
          # - --cmake-version=3.20 --os=linux
          - --cmake-version=3.28 --os=linux
          # - --cmake-version=3.14 --os=Linux 
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build ${{ matrix.cpu_arch }} for CXX ${{ matrix.cxx }} and CMAKE ${{ matrix.cmake }}
        uses: docker/build-push-action@v5
        with:
          context: .
          file: .github/workflows/Dockerfile
          load: true
          tags: ${{ env.TEST_TAG }}
          build-args: 
            --build-arg OS=ubuntu 
            --build-arg CPU_ARCH=${{ matrix.cpu_arch.docker }}
      - name: ${{ matrix.cpu_arch.cmake }}, CXX ${{ matrix.cxx }},${{ matrix.cmake }}
        run: |
           docker run --privileged --rm ${{ env.TEST_TAG }} sh -c \
            "cd robo_agents && sudo sh ./build_and_test.sh \
              --cpu-arch=${{ matrix.cpu_arch.cmake }} \
              --cxx-std=${{ matrix.cxx }} \
              ${{ matrix.cmake }} "