name: Build and Test on Docker
on:
  push:
    branches: 
      - main
      - ci
  pull_request:
    branches: 
      - main
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test on Docker
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Build and Test
        run: docker build -t local - < ./.github/workflows/Dockerfile
      - name: Run tests
        run: docker run -it local ./.github/workflows/build_and_test.sh

