name: Build and Test on Ubuntu
on:
  push:
    branches: [ main, ci ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-test:
    name: Testing on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        #  os: [ubuntu-20.04, macos-latest, windows-latest]
        os: [ubuntu-20.04]
    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0
    - name: Install dependencies
      run: |
        sh ./build_and_test.sh
