name: Build and Test on Ubuntu, MacOS, and Windows

# TODO(speralta): Add MacOS and Windows to the matrix
# Add Different C++, Python, C compilers to the matrix
# Add different versions of CMake to the matrix
# Add different OS versions to the matrix
on:
    push:
        branches: 
        - main
        - ci
    pull_request:
        branches: 
        - main
    workflow_dispatch:

permissions:
    contents: read
    pull-requests: write

jobs:
  build-and-test:
    name: Testing on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        #  os: [ubuntu-20.04, macos-latest, windows-latest]
        os: [ubuntu-20.04]
    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0
    - name: Install dependencies
      run: |
        sh ./.github/workflows/build_and_test.sh
