name: C++11, C++14, C++17, C++20, Ubuntu 16.04, 18.04, 20.04, latest

# TODO(speralta): Add MacOS and Windows to the matrix
# Add Different C++, Python, C compilers to the matrix
# Add different Linux OS versions to the matrix
# See https://stackoverflow.com/questions/66025220/paired-values-in-github-actions-matrix
on:
  push:
      branches: 
      - main
      - ci
  pull_request:
      branches: 
      - main
  workflow_dispatch:

permissions:
    contents: read
    pull-requests: write

jobs:
  ubuntu:
    name: Test on ${{ matrix.os }} with C++${{ matrix.cxx }}, CMake ${{ matrix.cmake }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        #  os: [ubuntu-20.04, macos-latest, windows-latest]
        os: [ubuntu-16.04, ubuntu-20.04, ubuntu-latest]
        cxx: [11, 14, 17, 20]
        cmake:
          - --cmake-version=3.14 --os=Linux 
          - --cmake-version=3.20 --os=linux
          - --cmake-version=3.28 --os=linux
    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0
    - name: Run ubuntu tests
      run: |
        apt-get update && apt-get upgrade -y && \
        apt-get install sudo && \ 
        sudo chmod +rwx /usr/local && \
        sudo sh .github/workflows/build_and_test.sh \
          --cpu-arch=x86_64 -i \
          --cxx-std=${{ matrix.cxx }} \
          ${{ matrix.cmake }}