name: "C++ 11|14|17|20| Ubuntu 22.04|20.04|18.04 "

# TODO(speralta): Add MacOS and Windows to the matrix
# Add Different C++, Python, C compilers to the matrix
# Add different Linux OS versions to the matrix
# See https://stackoverflow.com/questions/66025220/paired-values-in-github-actions-matrix
on:
  push:
      branches: 
      - main
      - ci
  pull_request:
      branches: 
      - main
  workflow_dispatch:

permissions:
    contents: read
    pull-requests: write

jobs:
  ubuntu:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        #  os: [ubuntu-20.04, macos-latest, windows-latest]
        os: [ubuntu-18.04, ubuntu-20.04, ubuntu-latest]
        cmake:
          - --cmake-version=3.14 --os=Linux 
          # - --cmake-version=3.20 --os=linux
          - --cmake-version=3.28 --os=linux
    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0
    - name: c++20
      run: |
        apt-get update && apt-get upgrade -y && \
        apt-get install sudo && \ 
        sudo chmod +rwx /usr/local && \
        sudo sh .github/workflows/build_and_test.sh \
          --cpu-arch=x86_64 -i \
          --cxx-std=20 \
          ${{ matrix.cmake }}
    - name: c++17
      run: |
        apt-get update && apt-get upgrade -y && \
        apt-get install sudo && \ 
        sudo chmod +rwx /usr/local && \
        sudo sh .github/workflows/build_and_test.sh \
          --cpu-arch=x86_64 -i \
          --cxx-std=17 \
          ${{ matrix.cmake }}
    - name: c++14
      run: |
          apt-get update && apt-get upgrade -y && \
          apt-get install sudo && \ 
          sudo chmod +rwx /usr/local && \
          sudo sh .github/workflows/build_and_test.sh \
            --cpu-arch=x86_64 -i \
            --cxx-std=14 \
            ${{ matrix.cmake }}
    - name: c++11
      run: |
          apt-get update && apt-get upgrade -y && \
          apt-get install sudo && \ 
          sudo chmod +rwx /usr/local && \
          sudo sh .github/workflows/build_and_test.sh \
            --cpu-arch=x86_64 -i \
            --cxx-std=11 \
            ${{ matrix.cmake }}
